name: intaker
channels:
- intake
- pyviz
- defaults
- conda-forge
dependencies:
- python=3.6
- ruamel_yaml=0.15
- intake>=0.1.5
- us_crime
- notebook
- ipykernel
- hvplot
- pygithub
- airline_flights
- ipywidgets
